config/routes.rb
Rails.application.routes.draw do
  resources :repeat_recurrences
  resources :daily_tasks
  resources :trackers
  resources :projects
  resources :weekly_goals
  resources :project_umbrellas

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'trackers#index'

  get '/index', to: 'trackers#index', as: 'index' #for rerouting back to index when month is chosen
  get '/month_index', to: 'trackers#month_index', as: 'month_index'
  get '/complete_task_from_tracker', to: 'trackers#complete_task_from_tracker', as: 'complete_task_from_tracker'
  get '/create_task_tracker', to: 'trackers#create_task_tracker', as: 'create_task_tracker'

  get '/complete_task', to: 'daily_tasks#complete_task', as: 'complete_task'
  get '/undo_complete_task', to: 'daily_tasks#undo_complete_task', as: 'undo_complete_task'
  get '/delete_task', to: 'daily_tasks#delete_task', as: 'delete_task'
  get '/nightly_task_processing', to: 'daily_tasks#nightly_task_processing', as: 'nightly_task_processing'
  get '/mark_today_task', to: 'daily_tasks#mark_today_task', as: 'mark_today_task'
  get '/remove_today_task', to: 'daily_tasks#remove_today_task', as: 'remove_today_task'
  get '/hide_completed_tasks', to: 'daily_tasks#hide_completed_tasks', as: 'hide_completed_tasks'

  get '/complete_goal', to: 'weekly_goals#complete_goal', as: 'complete_goal'
  get '/new_inherited_task', to: 'weekly_goals#new_inherited_task', as: 'new_inherited_task'
  get '/delete_goal', to: 'weekly_goals#delete_goal', as: 'delete_goal'

  post '/delete_project_and_wgs', to: 'projects#delete_project_and_wgs', as: 'delete_project_and_wgs'

  post '/delete_project_umbrella_and_projects', to: 'project_umbrellas#delete_project_umbrella_and_projects', as: 'delete_project_umbrella_and_projects'

  post '/new_dt_inherited_task', to: 'daily_tasks#new_inherited_task', as: 'new_dt_inherited_task'
end

app/models/project_umbrella.rb
class ProjectUmbrella < ApplicationRecord

	has_many :projects

	validates_presence_of :name #name is a required field

	#instance method to check for any associated projects
	def children?
		projects.any?
	end

	def get_children_string
		project_array = projects.all.collect {|p| [ p.name ] }
		project_string = project_array.map(&:inspect).to_s
		return project_string
	end

	def get_children
		project_array = projects.all
	end
end

app/controllers/project_umbrellas_controller.rb
class ProjectUmbrellasController < ApplicationController
  before_action :set_project_umbrella, only: [:show, :edit, :update, :destroy]

  # GET /project_umbrellas
  # GET /project_umbrellas.json
  def index
    @project_umbrellas = ProjectUmbrella.all
  end

  # GET /project_umbrellas/1
  # GET /project_umbrellas/1.json
  def show
  end

  # GET /project_umbrellas/new
  def new
    @project_umbrella = ProjectUmbrella.new
  end

  # GET /project_umbrellas/1/edit
  def edit
  end

  # POST /project_umbrellas
  # POST /project_umbrellas.json
  def create
    @project_umbrella = ProjectUmbrella.new(project_umbrella_params)

    respond_to do |format|
      if @project_umbrella.save
        # When a new project umbrella is created, its most likely because you also want to create a new project or task under that umbrella. Redirect to Project Creation Page to save clicks.
        format.html { redirect_to new_project_path(:project_umbrella_id => @project_umbrella.id), notice: 'Project umbrella was successfully created.' }
        format.json { render :new, status: :ok, location: @project } 
      else
        format.html { render :new }
        format.json { render json: @project_umbrella.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_umbrellas/1
  # PATCH/PUT /project_umbrellas/1.json
  def update
    respond_to do |format|
      if @project_umbrella.update(project_umbrella_params)
        format.html { redirect_to projects_url, notice: 'Project umbrella was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_umbrella }
      else
        format.html { render :edit }
        format.json { render json: @project_umbrella.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_umbrellas/1
  # DELETE /project_umbrellas/1.json
  def destroy
    if @project_umbrella.children? #warn user about deleting project umbrella with associated projects
      project_umbrella_id = @project_umbrella.id.to_s
      assoc_proj_list = @project_umbrella.get_children_string #instance methods
      assoc_projects = @project_umbrella.get_children
      assoc_wgs_list = '' #initialize variable to avoid null error
      assoc_projects.each do |assoc_proj| #loop through all associated projects
        if assoc_proj.children? #if there are any associated weekly goals
          assoc_wgs = assoc_proj.get_children_string
          if assoc_wgs.nil? then assoc_wgs = '' end #null handling
          assoc_wgs_list = assoc_wgs_list + assoc_wgs #concatenate list of associated weekly goals
        end
      end
      respond_to do |format|
        format.html
        format.js { render :js => "delete_pu_children("+project_umbrella_id+","+assoc_proj_list+","+assoc_wgs_list+");" } #confirmation window about whether to delete all children
      end 
    else #if project umbrella has no children, just destroy umbrella and be done with it
      @project_umbrella.destroy

      respond_to do |format|
        format.html { redirect_to projects_url, notice: 'Project umbrella was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def delete_project_umbrella_and_projects #called from application.js function delete pu children
    project_umbrella = ProjectUmbrella.find(params[:project_umbrella_id]) #find project umbrella based on ajax call parameter
    assoc_projects = project_umbrella.get_children # get all associated projects

    assoc_projects.each do |assoc_proj| #loop through all associated projects
      project = Project.find(assoc_proj.id)
      assoc_wgs = project.get_children #get all associated weekly goals
      WeeklyGoal.destroy(assoc_wgs.map(&:id)) #destroy all associated weekly goals
    end

    Project.destroy(assoc_projects.map(&:id)) #destroy all associated projects

    project_umbrella.destroy #destroy project umbrella

    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project Umbrella was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_umbrella
      @project_umbrella = ProjectUmbrella.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_umbrella_params
      params.require(:project_umbrella).permit(:name, :projects)
    end
end

app/helpers/project_umbrellas_helper.rb
module ProjectUmbrellasHelper
end

app/views/project_umbrellas/_form.html.erb
<%= form_with(model: project_umbrella, local: true) do |form| %>
  <% if project_umbrella.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project_umbrella.errors.count, "error") %> prohibited this project_umbrella from being saved:</h2>

      <ul>
      <% project_umbrella.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/project_umbrellas/edit.html.erb
<h1>Editing Project Umbrella</h1>

<%= render 'form', project_umbrella: @project_umbrella %>

<%= link_to 'Back', project_umbrellas_path %>

app/views/project_umbrellas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Project Umbrellas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_umbrellas.each do |project_umbrella| %>
      <tr>
        <td><%= project_umbrella.name %></td>
        <td><%= link_to 'Show', project_umbrella %></td>
        <td><%= link_to 'Edit', edit_project_umbrella_path(project_umbrella) %></td>
        <td><%= link_to 'Destroy', project_umbrella, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project Umbrella', new_project_umbrella_path %>

app/views/project_umbrellas/new.html.erb
<h1>New Project Umbrella</h1>

<%= render 'form', project_umbrella: @project_umbrella %>

<%= link_to 'Back', projects_path %>

app/views/project_umbrellas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_project_umbrella_path(@project_umbrella) %> |
<%= link_to 'Back', project_umbrellas_path %>