config/routes.rb
Rails.application.routes.draw do
  resources :repeat_recurrences
  resources :daily_tasks
  resources :trackers
  resources :projects
  resources :weekly_goals
  resources :project_umbrellas

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'trackers#index'

  get '/index', to: 'trackers#index', as: 'index' #for rerouting back to index when month is chosen
  get '/month_index', to: 'trackers#month_index', as: 'month_index'
  get '/complete_task_from_tracker', to: 'trackers#complete_task_from_tracker', as: 'complete_task_from_tracker'
  get '/create_task_tracker', to: 'trackers#create_task_tracker', as: 'create_task_tracker'

  get '/complete_task', to: 'daily_tasks#complete_task', as: 'complete_task'
  get '/undo_complete_task', to: 'daily_tasks#undo_complete_task', as: 'undo_complete_task'
  get '/delete_task', to: 'daily_tasks#delete_task', as: 'delete_task'
  get '/nightly_task_processing', to: 'daily_tasks#nightly_task_processing', as: 'nightly_task_processing'
  get '/mark_today_task', to: 'daily_tasks#mark_today_task', as: 'mark_today_task'
  get '/remove_today_task', to: 'daily_tasks#remove_today_task', as: 'remove_today_task'
  get '/hide_completed_tasks', to: 'daily_tasks#hide_completed_tasks', as: 'hide_completed_tasks'

  get '/complete_goal', to: 'weekly_goals#complete_goal', as: 'complete_goal'
  get '/new_inherited_task', to: 'weekly_goals#new_inherited_task', as: 'new_inherited_task'
  get '/delete_goal', to: 'weekly_goals#delete_goal', as: 'delete_goal'

  post '/delete_project_and_wgs', to: 'projects#delete_project_and_wgs', as: 'delete_project_and_wgs'

  post '/delete_project_umbrella_and_projects', to: 'project_umbrellas#delete_project_umbrella_and_projects', as: 'delete_project_umbrella_and_projects'

  post '/new_dt_inherited_task', to: 'daily_tasks#new_inherited_task', as: 'new_dt_inherited_task'
end

app/models/weekly_goal.rb
class WeeklyGoal < ApplicationRecord

	belongs_to :project
	has_many :daily_tasks

	validates_presence_of :name #name is a required field

	def active_task_num
		daily_tasks.where(:active => true).count
	end
	
end

app/controllers/weekly_goals_controller.rb
class WeeklyGoalsController < ApplicationController
  before_action :set_weekly_goal, only: [:show, :edit, :update, :destroy]

  # GET /weekly_goals
  # GET /weekly_goals.json
  def index
    @weekly_goals = WeeklyGoal.all
  end
 
  # GET /weekly_goals/1
  # GET /weekly_goals/1.json
  def show
  end

  # GET /weekly_goals/new
  def new
    @weekly_goal = WeeklyGoal.new
    if !params[:project_umbrella_id].nil? then
      @project_umbrella = ProjectUmbrella.find(params[:project_umbrella_id]) #if project_umbrella was passed in from project create function
    end
    if !params[:project_id].nil? then
      @project = Project.find(params[:project_id]) #if project was passed in from project create function
    end

    respond_to do |format|
      format.html 
      format.js
    end
  end

  def new_inherited_task
    @weekly_goal = WeeklyGoal.find(params[:weekly_goal])
    @daily_task = DailyTask.new
    @project_umbrella = ProjectUmbrella.find(@weekly_goal.project_umbrella_id)
    @project = Project.find(@weekly_goal.project_id)

    respond_to do |format|
      format.json
      format.html
      format.js
    end
  end

  # GET /weekly_goals/1/edit
  def edit
    @weekly_goal = WeeklyGoal.find(params[:id])

    respond_to do |format|
      format.json
      format.html
      format.js
    end
  end

  # POST /weekly_goals
  # POST /weekly_goals.json
  def create
    @weekly_goal = WeeklyGoal.new(weekly_goal_params)

    respond_to do |format|
      if @weekly_goal.save
        format.html
        #format.html { redirect_to request.referer, notice: 'Weekly Goal was successfully created.' } #refresh page where 'new' button was clicked
        format.json { render :show, status: :created, location: @weekly_goal }
      else
        format.html { render :new }
        format.json { render json: @weekly_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weekly_goals/1
  # PATCH/PUT /weekly_goals/1.json
  def update
    respond_to do |format|
      if @weekly_goal.update(weekly_goal_params)
        format.html { redirect_to request.referer, notice: 'Weekly Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @weekly_goal }
      else
        format.html { render :edit }
        format.json { render json: @weekly_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  def complete_goal
    @weekly_goal = weekly_goal.find(params[:goal_id])
    @weekly_goal.update_attribute(:completed,true)
    respond_to do |format|
      format.html { redirect_to '/', notice: 'Weekly Goal was successfully completed.' }
      format.json { head :no_content }
    end
  end

  def delete_goal
    @weekly_goal = WeeklyGoal.find(params[:goal_id])
    @weekly_goal.destroy
    respond_to do |format|
      format.html { redirect_to '/', notice: 'Weekly Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # DELETE /weekly_goals/1
  # DELETE /weekly_goals/1.json
  def destroy
    @weekly_goal.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Weekly Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weekly_goal
      @weekly_goal = WeeklyGoal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weekly_goal_params
      params.require(:weekly_goal).permit(:name, :project_id, :completed, :repeat_recurrence_id, :active, :project_umbrella_id)
    end
end

app/helpers/weekly_goals_helper.rb
module WeeklyGoalsHelper
end

app/views/weekly_goals/_edit_form.html.erb
<%= javascript_include_tag "project_selectors" %> <!-- PULL IN FUNCTIONALITY FOR LIMITING SELECTION LISTS BASED ON PREVIOUS SELECTION -->

<!-- INITIALIZE VARIABLES -->
<% weekly_goal = weekly_goal %> <!-- generate local variable from local pulled in from render partial in edit.js.erb. local variable isn't recognized if I don't have this line included -->
<% if weekly_goal.nil? then weekly_goal = WeeklyGoal.new end%> <!-- null handling to satisfy compiler -->
<%  project_umbrellas = ProjectUmbrella.all %>


<!-- FORM -->
<%= form_for weekly_goal do |form| %>

  <!-- ERROR HANDLING -->
  <% if weekly_goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(weekly_goal.errors.count, "error") %> prohibited this weekly_goal from being saved:</h2>

      <ul>
      <% weekly_goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- FORM FIELDS -->
  <div>
    <%= form.label :project_umbrella %>
    <% if !weekly_goal.project.nil? %>
      <% if !weekly_goal.project.project_umbrella_id.nil? %>
        <%= form.select :project_umbrella_id, options_from_collection_for_select(project_umbrellas, "id", "name" ,weekly_goal.project.project_umbrella_id) + options_for_select(["Add New..."]) %>
      <% else %>
        <%= form.select :project_umbrella_id, options_from_collection_for_select(project_umbrellas, "id", "name") + options_for_select(["Add New..."]) %>
      <% end %>
    <% end %>
  </div>

  <div>
    <%= form.label :project %>
    <%= form.grouped_collection_select :project_id, ProjectUmbrella.order(:name), :projects, :name, :id, :name, {:include_blank => "Add New..."}, :value => weekly_goal.project_id %>
  </div>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :repeat_recurrence %>
    <%= form.select :repeat_recurrence_id, RepeatRecurrence.all.collect{ | rr | [rr.name, rr.id] }, :value => weekly_goal.repeat_recurrence_id %>
  </div>

  <div>
    <%= form.label "Active?: " %>
    <%= form.check_box :active, :value => weekly_goal.active %>
  </div>

  <div>
    <%= form.label "Completed?: " %>
    <%= form.check_box :completed, :value => weekly_goal.completed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/weekly_goals/_new_form.html.erb
<%= javascript_include_tag "project_selectors" %> <!-- PULL IN FUNCTIONALITY FOR LIMITING SELECTION LISTS BASED ON PREVIOUS SELECTION -->
<%= javascript_include_tag "modals_dropdowns" %>

<!-- INITIALIZE VARIABLES -->
<% weekly_goal = weekly_goal %> <!-- generate local variable from local pulled in from render partial in new.js.erb. local variable isn't recognized if I don't have this line included -->
<% if weekly_goal.nil? then weekly_goal = WeeklyGoal.new end%> <!-- null handling to satisfy compiler -->
 <%  project_umbrellas = ProjectUmbrella.all %> 

  <!-- FORM  -->
<%= form_for weekly_goal do |form| %>

  <!-- ERROR HANDLING -->
  <% if weekly_goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(weekly_goal.errors.count, "error") %> prohibited this weekly_goal from being saved:</h2>

      <ul>
      <% weekly_goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- FORM FIELDS -->
  <div class="modal-field">
    <% if !@project_umbrella.nil? then %> <!-- if 'new weekly goal' is called from 'new Project' section, default in project umbrella -->
      <%= form.label :project_umbrella, 'Project Umbrella: '+@project_umbrella.name %>

      <%= form.hidden_field :project_umbrella_id, :value=> @project_umbrella.id %>
    <% else %> <!-- if 'new project' is called from Projects section, display full project umbrella list -->
      <%= form.label :project_umbrella, 'Project Umbrella: ' %>
      <%= form.select :project_umbrella_id, options_from_collection_for_select(project_umbrellas, "id", "name") + options_for_select(["Add New..."]), prompt: "(Select a Project Umbrella)" %>
    <% end %>
  </div>

  <div class="modal-field">
    <% if !@project.nil? then %> <!-- if 'new weekly goal' is called from 'new Project' section, default in project -->
      <%= form.label :project, 'Project: '+@project.name %>

      <%= form.hidden_field :project_id, :value=> @project.id %>
    <% else %> <!-- if 'new weekly goal' is called from Projects section, display full project list -->
      <%= form.label :project, 'Project: ' %>
       <%= form.grouped_collection_select :project_id, ProjectUmbrella.order(:name), :projects, :name, :id, :name, {:prompt => "(Select a Project)", :include_blank => "Add New..."} %>
    <% end %>
  </div>

  <div class="modal-field">
    <%= form.label :name, 'Name: ' %>
    <%= form.text_field :name %>
  </div>

  <div class="modal-field">
    <%= form.label :repeat_recurrence, 'Repeat Recurrence: ' %>
    <%= form.select :repeat_recurrence_id, options_for_select(RepeatRecurrence.all.collect{ | rr | [rr.name, rr.id] }) %>
  </div>

  <div class="modal-field">
    <%= form.hidden_field :active, :value => true %>
    <%= form.hidden_field :completed, :value => false %>
  </div>


  <div class="modal-actions modal-footer">
    <%= form.submit 'Create Weekly Goal', {:class => 'btn btn-secondary modal-create-task-btn', 'data-toggle' => "modal", 
      :href => "#task-goal-modal-window2", :onclick => "cascadeWGModal();"} %>

    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
  </div>

<% end %>

app/views/weekly_goals/edit.html.erb
<h1>Editing Weekly Goal</h1>

<%= render 'edit_form', weekly_goal: @weekly_goal %>

<%= link_to 'Back', projects_path %>

app/views/weekly_goals/edit.js.erb
// populate modal
document.getElementById("task-goal-modal-title").innerHTML="Edit Weekly Goal";
 
$('#task-goal-modal-window-body').html("<%= j render partial: 'weekly_goals/edit_form', locals: {weekly_goal: @weekly_goal} %>");

// render modal
$('#task-goal-modal-window').modal('show');

app/views/weekly_goals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Weekly Goals</h1>

<table>
  <thead>
    <tr>
      <td>Project Umbrella</td>
      <td>Project</td>
      <td>Name</td>
      <td>Repeat Recurrence</td>
      <td>Completed?</td>
      <td>Active?</td>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weekly_goals.each do |weekly_goal| %>
      <tr>
        <td><%= weekly_goal.project_umbrella_id %></td>
        <td><%= weekly_goal.project_id %></td>
        <td><%= weekly_goal.name %></td>
        <td><%= weekly_goal.repeat_recurrence_id %></td>
        <td><%= weekly_goal.completed %></td>
        <td><%= weekly_goal.active %></td>
        <td><%= link_to 'Show', weekly_goal %></td>
        <td><%= link_to 'Edit', edit_weekly_goal_path(weekly_goal) %></td>
        <td><%= link_to 'Destroy', weekly_goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weekly Goal', new_weekly_goal_path %>

app/views/weekly_goals/new.html.erb
<h1>New Weekly Goal</h1>

<%= render 'new_form', weekly_goal: @weekly_goal %>

<%= link_to 'Back', projects_path %>

app/views/weekly_goals/new.js.erb
// populate modal
document.getElementById("task-goal-modal-title").innerHTML="New Weekly Goal";
$('#task-goal-modal-window-body').html("<%= j render partial: 'weekly_goals/new_form', locals: {weekly_goal: @weekly_goal} %>");

// render modal
$('#task-goal-modal-window').modal('show');

app/views/weekly_goals/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_weekly_goal_path(@weekly_goal) %> |
<%= link_to 'Back', weekly_goals_path %>