config/routes.rb
Rails.application.routes.draw do
  resources :repeat_recurrences
  resources :daily_tasks
  resources :trackers
  resources :projects
  resources :weekly_goals
  resources :project_umbrellas

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'trackers#index'

  get '/index', to: 'trackers#index', as: 'index' #for rerouting back to index when month is chosen
  get '/month_index', to: 'trackers#month_index', as: 'month_index'
  get '/complete_task_from_tracker', to: 'trackers#complete_task_from_tracker', as: 'complete_task_from_tracker'
  get '/create_task_tracker', to: 'trackers#create_task_tracker', as: 'create_task_tracker'

  get '/complete_task', to: 'daily_tasks#complete_task', as: 'complete_task'
  get '/undo_complete_task', to: 'daily_tasks#undo_complete_task', as: 'undo_complete_task'
  get '/delete_task', to: 'daily_tasks#delete_task', as: 'delete_task'
  get '/nightly_task_processing', to: 'daily_tasks#nightly_task_processing', as: 'nightly_task_processing'
  get '/mark_today_task', to: 'daily_tasks#mark_today_task', as: 'mark_today_task'
  get '/remove_today_task', to: 'daily_tasks#remove_today_task', as: 'remove_today_task'
  get '/hide_completed_tasks', to: 'daily_tasks#hide_completed_tasks', as: 'hide_completed_tasks'

  get '/complete_goal', to: 'weekly_goals#complete_goal', as: 'complete_goal'
  get '/new_inherited_task', to: 'weekly_goals#new_inherited_task', as: 'new_inherited_task'
  get '/delete_goal', to: 'weekly_goals#delete_goal', as: 'delete_goal'

  post '/delete_project_and_wgs', to: 'projects#delete_project_and_wgs', as: 'delete_project_and_wgs'

  post '/delete_project_umbrella_and_projects', to: 'project_umbrellas#delete_project_umbrella_and_projects', as: 'delete_project_umbrella_and_projects'

  post '/new_dt_inherited_task', to: 'daily_tasks#new_inherited_task', as: 'new_dt_inherited_task'
end

app/models/project.rb
class Project < ApplicationRecord

	has_many :weekly_goals
	belongs_to :project_umbrella, optional: true
	has_many :daily_tasks
	has_many :trackers

	validates_presence_of :name #name is a required field

	#instance method to check for any associated projects
	def children?
		weekly_goals.any?
	end

	def get_children_string
		wg_array = weekly_goals.all.collect {|wg| [ wg.name ] }
		wg_string = wg_array.map(&:inspect).to_s
		return wg_string
	end

	def get_children
		wg_array = weekly_goals.all
	end
	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    #PROJECT UMBRELLAS
    @project_umbrellas = ProjectUmbrella.all

    #WEEKLY GOALS
    @weekly_goals = WeeklyGoal.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    if !params[:project_umbrella_id].nil? then
      @project_umbrella = ProjectUmbrella.find(params[:project_umbrella_id]) #if project_umbrella was passed in from project umbrella create function
    end
  end

  # GET /projects/1/edit
  def edit
    @project_umbrellas = ProjectUmbrella.all
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        # When a new project is created, its most likely because you also want to create a new weekly goal under that project. Redirect to Weekly Goal Creation Page to save clicks.
        format.html { redirect_to new_weekly_goal_path(:project_id => @project.id, :project_umbrella_id => @project.project_umbrella_id), notice: 'Project umbrella was successfully created.' }
        
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_url, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    if @project.children? #warn user about deleting project umbrella with associated projects
        project_id = @project.id.to_s
        assoc_wgs = @project.get_children_string
        
        respond_to do |format|
          format.html
          format.js { render :js => "delete_p_children("+project_id+","+assoc_wgs+");" } #confirmation window about whether to delete all children
        end
   
    else
      @project.destroy
      respond_to do |format|
        format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def delete_project_and_wgs
      project = Project.find(params[:project_id]) #find project based on ajax call parameter
      assoc_wgs = project.get_children # get all associated weekly goals
      WeeklyGoal.destroy(assoc_wgs.map(&:id)) #destroy all associated projects

      project.destroy #destroy project umbrella

      respond_to do |format|
        format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
        format.json { head :no_content }
      end
  end



  #PROJECT UMBRELLA METHODS
  # GET /project/umbrella/new
  def new_project_umbrella
    @project_umbrella = ProjectUmbrella.new
  end

  ##############################################################################################

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :start_date, :completion_goal_date, :project_umbrella_id, :weekly_goals)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_edit_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name, value: project.name %>
  </div>

  <div>
    <%= form.label :associated_project_umbrella %>
    <%=form.select :project_umbrella_id, ProjectUmbrella.all.collect {|pu| [ pu.name, pu.id ] }, :value => project.project_umbrella_id %>
  </div>

  <div>
    <%= form.label :start_date %>
    <%= content_tag :div, :class => "date_select", :data => {:provide => 'datepicker', 'date-format' => 'yyyy-mm-dd', 'date-autoclose' => 'true'} do
      form.text_field :start_date, class: 'form-control', placeholder: 'YYYY-MM-DD', value: project.start_date
    end%>
  </div>

  <div>
    <%= form.label :completion_goal_date %>
    <%= content_tag :div, :class => "date_select", :data => {:provide => 'datepicker', 'date-format' => 'yyyy-mm-dd', 'date-autoclose' => 'true'} do
      form.text_field :completion_goal_date, class: 'form-control', placeholder: 'YYYY-MM-DD', value: project.completion_goal_date
    end%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_new_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <% if !@project_umbrella.nil? then %> <!-- if 'new project' is called from 'new Project Umbrella' section, default in project umbrella -->
      Project Umbrella: <%= @project_umbrella.name %>

      <%= form.hidden_field :project_umbrella_id, :value=> @project_umbrella.id %>
    <% else %> <!-- if 'new project' is called from Projects section, display full project umbrella list -->
      <%= form.label :associated_project_umbrella %>
      <%=form.select :project_umbrella_id, ProjectUmbrella.all.collect {|pu| [ pu.name, pu.id ] } %>
    <% end %>
  </div>

  <div>
    <%= form.label :start_date %>
    <%= content_tag :div, :class => "date_select", :data => {:provide => 'datepicker', 'date-format' => 'yyyy-mm-dd', 'date-autoclose' => 'true'} do
      form.text_field :start_date, class: 'form-control', placeholder: 'YYYY-MM-DD', value: Time.now.strftime('%Y-%m-%d')
    end%>
  </div>

  <div>
    <%= form.label :completion_goal_date %>
    <%= content_tag :div, :class => "date_select", :data => {:provide => 'datepicker', 'date-format' => 'yyyy-mm-dd', 'date-autoclose' => 'true'} do
      form.text_field :completion_goal_date, class: 'form-control', placeholder: 'YYYY-MM-DD', value: Time.now.strftime('%Y-%m-%d')
    end%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/delete_children.js.erb
	alert('test!');

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'edit_form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>  
  

  <!-- JAVASCRIPT (assets/javascripts) -->
  <%= javascript_include_tag "project_selectors" %>
  <%= javascript_include_tag "modals_dropdowns" %>
</head>
<body>
  <p id="notice"><%= notice %></p>

  <!-- BOOTSTRAP - NAVBAR -->
  <nav class="navbar nav-style">
    <span class="navbar-brand h1 action-button"><%= link_to "TimeTrack", "/", class: "action-btn-item", method: :get %></span> 
  </nav>

  <div class="action-button-container">
    <div id="project-go-home" class="action-button">
      <%= link_to "/", method: :get do %>
        <i class="fas fa-home action-btn-item" data-toggle="tooltip" data-placement="bottom" title="Home"></i>
      <% end %>
    </div>
    <div id="project-view-all-trackers" class="action-button">
      <%= link_to "month_index", method: :get, id: "tracker-index-nav-month-tracker-link" do %>
        <i class="fas fa-calendar-alt action-btn-item" data-toggle="tooltip" data-placement="bottom" title="View All Trackers"></i>
      <% end %>
    </div>   
  </div>
      
  <br><br><br><br>
  <h1>Project Umbrellas</h1>
  <%= link_to new_project_umbrella_path do %>
    <i class="fas fa-plus action-btn-item" data-toggle="tooltip" data-placement="top" title="New Project Umbrella"></i>
  <% end %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Associated Projects</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @project_umbrellas.each do |project_umbrella| %>
        <tr>
          <td><%= project_umbrella.name %></td>
          <td><%  project_umbrella.projects.each do |project| %>
                <%= project.name %><br>
              <% end %> 
          </td>
          <td><%= link_to edit_project_umbrella_path(project_umbrella) do %>
                <i class="far fa-edit" data-toggle="tooltip" data-placement="top" title="Edit"></i>
              <% end %>
          </td>
          <td><%= link_to project_umbrella, method: :delete, data: { confirm: 'Are you sure?' }, remote: true do %>
              <i class="far fa-trash-alt" data-toggle="tooltip" data-placement="top" title="Delete"></i>
            <% end %>
          </td> <!--link to modal window for 'Destroy' task functionality -->
        </tr>
      <% end %>
    </tbody>
  </table>

  <br><br>

  

  <br><br>

  <h1>Projects</h1>

  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Project Umbrella</th>
        <th>Start Date</th>
        <th>Completion Goal Date</th>
        <th>Associated Weekly Goal</th>
        <th>Associated Daily Tasks</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.id %></td>
          <td><%= project.name %></td>
          <td>
            <% if !project.project_umbrella.nil? then %>
              <%= project.project_umbrella.name %>
            <% end %>
          </td>
          <td><%= project.start_date %></td>
          <td><%= project.completion_goal_date %></td>
          <td><%  project.weekly_goals.each do |weekly_goal| %>
                <%= weekly_goal.name %><br>
              <% end %> 
          </td>
          <td><% project.daily_tasks.each do |task| %>
                <%= task.name %><br>
              <% end %>
          </td>
          <td><%= link_to edit_project_path(project) do %>
            <i class="far fa-edit" data-toggle="tooltip" data-placement="top" title="Edit"></i>
            <% end %>
          </td>
          <td><%= link_to project, method: :delete, data: { confirm: 'Are you sure?' }, remote: true do %>
              <i class="far fa-trash-alt" data-toggle="tooltip" data-placement="top" title="Delete"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>

  <%= link_to 'New Project', new_project_path %>

  <br><br>

  <h1>Weekly Goals</h1>

  <table>
    <thead>
      <tr>
        <th>Project Umbrella</th>
        <th>Project</th>
        <th>Name</th>
        <th>Repeat Recurrence</th>
        <th>Completed</th>
        <th>Active</th>
        <th>Associated Daily Tasks</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @weekly_goals.each do |weekly_goal| %>
        <tr>
          <td>
            <% if !weekly_goal.project.nil? then %>
              <% if !weekly_goal.project.project_umbrella.nil? then %>
                <%= weekly_goal.project.project_umbrella.name %>
              <% end %>
            <% end %>
          </td>
          <td>
            <% if !weekly_goal.project.nil? then %>
              <%= weekly_goal.project.name %>
            <% end %>
          </td>
          <td><%= weekly_goal.name %></td>
          <td>
            <% if !weekly_goal.repeat_recurrence_id.nil? then %>
              <%= RepeatRecurrence.find(weekly_goal.repeat_recurrence_id).name %>
            <% end %>
          </td>
          <td><%= weekly_goal.completed %></td>
          <td><%= weekly_goal.active %></td>
          <td><% weekly_goal.daily_tasks.each do |task| %>
                <%= task.name %><br>
              <% end %>
          </td>
          <td><%= link_to edit_weekly_goal_path(weekly_goal) do %>
              <i class="far fa-edit" data-toggle="tooltip" data-placement="top" title="Edit"></i>
            <% end %>
          </td>
          <td><%= link_to weekly_goal, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="far fa-trash-alt" data-toggle="tooltip" data-placement="top" title="Delete"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br><br>

  <%= link_to 'New Weekly Goal', new_weekly_goal_path %>


</body>
</html>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'new_form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Project Umbrella:</strong>
  <%= @project.project_umbrella_id %>
 </p>

<p>
  <strong>Start Date:</strong>
  <%= @project.start_date %>
</p>

<p>
  <strong>Completion Goal Date:</strong>
  <%= @project.completion_goal_date %>
</p>

<p>
  <strong>Associated Weekly Goals:</strong>
  
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>