config/routes.rb
Rails.application.routes.draw do
  resources :repeat_recurrences
  resources :daily_tasks
  resources :trackers
  resources :projects
  resources :weekly_goals
  resources :project_umbrellas

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'trackers#index'

  get '/index', to: 'trackers#index', as: 'index' #for rerouting back to index when month is chosen
  get '/month_index', to: 'trackers#month_index', as: 'month_index'
  get '/complete_task_from_tracker', to: 'trackers#complete_task_from_tracker', as: 'complete_task_from_tracker'
  get '/create_task_tracker', to: 'trackers#create_task_tracker', as: 'create_task_tracker'

  get '/complete_task', to: 'daily_tasks#complete_task', as: 'complete_task'
  get '/undo_complete_task', to: 'daily_tasks#undo_complete_task', as: 'undo_complete_task'
  get '/delete_task', to: 'daily_tasks#delete_task', as: 'delete_task'
  get '/nightly_task_processing', to: 'daily_tasks#nightly_task_processing', as: 'nightly_task_processing'
  get '/mark_today_task', to: 'daily_tasks#mark_today_task', as: 'mark_today_task'
  get '/remove_today_task', to: 'daily_tasks#remove_today_task', as: 'remove_today_task'
  get '/hide_completed_tasks', to: 'daily_tasks#hide_completed_tasks', as: 'hide_completed_tasks'

  get '/complete_goal', to: 'weekly_goals#complete_goal', as: 'complete_goal'
  get '/new_inherited_task', to: 'weekly_goals#new_inherited_task', as: 'new_inherited_task'
  get '/delete_goal', to: 'weekly_goals#delete_goal', as: 'delete_goal'

  post '/delete_project_and_wgs', to: 'projects#delete_project_and_wgs', as: 'delete_project_and_wgs'

  post '/delete_project_umbrella_and_projects', to: 'project_umbrellas#delete_project_umbrella_and_projects', as: 'delete_project_umbrella_and_projects'

  post '/new_dt_inherited_task', to: 'daily_tasks#new_inherited_task', as: 'new_dt_inherited_task'
end

app/models/tracker.rb
class Tracker < ApplicationRecord

	belongs_to :daily_task, optional: true
    belongs_to :project, optional: true
	accepts_nested_attributes_for :daily_task #this allows the 'add tracker' button in the task section to complete a task

	 # after_initialize :get_month

	# extrapolate the month based on the current date
    # def get_month
    #   	self.month ||= Time.now.month
    # end

    def update_month
    	self.month ||= self.date.month
  	end
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  before_action :set_tracker, only: [:show, :edit, :update, :destroy]

  helper_method :get_prev_month_year, :get_days_trackers, :get_outstanding_weekly_goals, :get_completed_weekly_goals, :get_daily_tasks, :get_unassoc_daily_tasks, :new_daily_task_initialize, :complete_task, :get_todays_outstanding_tasks, :get_todays_completed_tasks


  # GET /trackers
  # GET /trackers.json
  #limit to only trackers within the specified month, ordered with most recent date first
  def index

    #TRACKERS
    month=params[:month]
    year=params[:year]
      if month.nil? or year.nil? then 
        @month=Time.now.month 
        @year=Time.now.year
      else 
        @month=month.to_i
        @year=year.to_i
      end

      #WEEKLY GOALS
      # => Group Weekly Goals by Project Umbrella for grouped display in index
      @weekly_goal_categories = ProjectUmbrella.joins(:projects => [:weekly_goals]).pluck(:name).uniq #avoid duplicates

      #PROJECT INFRASTRUCTURE
      @projects = Project.all 
      @weekly_goals = WeeklyGoal.all 
      @daily_tasks = DailyTask.all 


  end

  def month_index
    month=params[:month]
    year=params[:year]
      if month.nil? or year.nil? then 
        @month=Time.now.month 
        @year=Time.now.year
      else 
        @month=month.to_i
        @year=year.to_i
      end
  end

  # GET /trackers/1
  # GET /trackers/1.json
  def show
  end

  # GET /trackers/new
  def new
    #initialize globals
    @tracker = Tracker.new
    @projects = Project.all 
    @weekly_goals = WeeklyGoal.all 
    @daily_tasks = DailyTask.all 
  end

  # GET /trackers/1/edit
  def edit 
    #initialize globals
      @tracker = Tracker.find(params[:id])
      @projects = Project.all 
      @weekly_goals = WeeklyGoal.all 
      @daily_tasks = DailyTask.all 

      respond_to do |format|
        format.js 
        format.html { redirect_to '/', notice: 'Tracker was successfully updated.' }
        format.json
      end

  end

  # POST /trackers
  # POST /trackers.json
  def create
    @tracker = Tracker.new(tracker_params)
    @tracker.update_month #default the month number from the date into the month column

    respond_to do |format|
      if @tracker.save
        format.js
        format.html { redirect_to '/', notice: 'Tracker was successfully created.' }
        format.json #{ render :show, status: :created, location: @tracker }
      else
        format.js
        format.html { render :new }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_task_tracker

    @task = DailyTask.find(params[:task_id])

    respond_to do |format|
      format.json
      format.html
      format.js
    end
  end

  # PATCH/PUT /trackers/1
  # PATCH/PUT /trackers/1.json
  def update
    #PROJECT INFRASTRUCTURE
      @projects = Project.all 
      @weekly_goals = WeeklyGoal.all 
      @daily_tasks = DailyTask.all 

    respond_to do |format|
      if @tracker.update(tracker_params)
        format.html { redirect_to request.referer, notice: 'Tracker was successfully updated.' } #refresh page where 'edit' button was clicked
        format.json #{ render :show, status: :ok, location: @tracker }
      else
        format.html { render :edit }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trackers/1
  # DELETE /trackers/1.json
  def destroy
    @tracker.destroy
    respond_to do |format|
      format.html { redirect_to request.referer, notice: 'Tracker was successfully destroyed.' } #refresh page where 'edit' button was clicked
      format.json { head :no_content }
    end
  end


  def complete_task_from_tracker
    @daily_task.update_attribute(:completed,true)
    respond_to do |format|
      format.html { redirect_to '/', notice: 'Daily Task was successfully completed.' }
      format.json { head :no_content }
    end
  end


  private

  #########################################################################
  ####                   HELPER METHODS FOR TRACKERS                   ####
  #########################################################################
    # Use callbacks to share common setup or constraints between actions.
    def set_tracker
      @tracker = Tracker.find(params[:id])
    end

    def get_prev_month_year dir
      curr_month_year = Date.new(@year,@month,1)
      if dir=="-" then
        if curr_month_year.mon == 1 then
          incr_month = {"month" => (curr_month_year - 1.months).month, "year" => (curr_month_year - 1.years).year}
        else 
          incr_month = {"month" => (curr_month_year - 1.months).month, "year" => curr_month_year.year}
        end
      else 
        if curr_month_year.mon == 12 then
          incr_month = {"month" => (curr_month_year + 1.months).month, "year" => (curr_month_year + 1.years).year}
        else 
          incr_month = {"month" => (curr_month_year + 1.months).month, "year" => curr_month_year.year}
        end
      end
      return incr_month
    end


    def get_days_trackers i
      @day_trackers = Tracker.where("CAST(EXTRACT(YEAR FROM date) AS integer) = ? AND month = ? AND CAST(EXTRACT(DAY FROM date) AS integer) = ?",@year, @month, i).all.order("date DESC")
     # @day_trackers = Tracker.where("CAST(strftime('%Y',date) AS integer) = ? AND month = ? AND CAST(strftime('%d',date) AS integer) = ?",@year,@month, i).all.order("date DESC")
    end

  #########################################################################
  ####        HELPER METHODS FOR DAILY TASKS AND WEEKLY GOALS          ####
  #########################################################################

  #remember that join references the model, but where references the table
    def get_outstanding_weekly_goals 
      includesOutsDT = WeeklyGoal.where('weekly_goals.id IN (?)', DailyTask.where("completed = ? AND active = ?",false,true).select(:weekly_goal_id))
      return includesOutsDT.all.order('weekly_goals.project_umbrella_id DESC')
    end

    def get_completed_weekly_goals(type)
      active_flag = true
      if type == 'active' then 
        active_flag = true
      else 
        active_flag = false
      end
      
      excludesOutsDT = WeeklyGoal.where('(weekly_goals.id NOT IN (?)) AND active = ?', DailyTask.where("completed = ? AND active = ?",false,true).select(:weekly_goal_id), active_flag);
      return excludesOutsDT.all.order('weekly_goals.project_umbrella_id DESC')
     
    end

    def get_daily_tasks wg_id 
      return DailyTask.where(:daily_tasks => {:active => true}).joins(:weekly_goal).where(:weekly_goals => {:id => wg_id}).all
      # return DailyTask.where(:daily_tasks => {:active => true}).joins(:weekly_goal => :project).where(:projects => {:id => project_id}).all
    end

    def get_todays_outstanding_tasks
      return DailyTask.where("is_today_task = ? AND active = ? AND completed = ?", true, true, false).all
    end

    def get_todays_completed_tasks
      return DailyTask.where("is_today_task = ? AND active = ? AND completed = ?", true, true, true).all
    end

    def get_unassoc_daily_tasks 
      # find daily tasks that do not have a weekly task that shares the same project
      unassoc_daily_tasks = []
      # loop through all daily tasks
      DailyTask.where("active = ?", true).each do |daily_task| 
        # if there is not weekly task associated with the same project, add to array
        unless WeeklyGoal.where("active = ? AND project_umbrella_id = ?", true, daily_task.project_umbrella_id).exists?
          unassoc_daily_tasks.push(daily_task)
        end
      end
      return unassoc_daily_tasks
    end

  #########################################################################
  ####                      TRACKER PARAM SIEVE                        ####
  #########################################################################

    # Never trust parameters from the scary internet, only allow the white list through.
    def tracker_params
      params.require(:tracker).permit(:date, :task, :subtask_1, :description, :hours, :start_time, :end_time, :payment, :month, :project_id, :weekly_goal_id, :daily_task_id, :project_umbrella_id, daily_task_attributes:[:completed])
    end
end

app/helpers/trackers_helper.rb
module TrackersHelper
end

app/views/trackers/_display.html.erb
        <td><%= @tracker.id %></td>

        <td><%= @tracker.date.strftime("%a #{@tracker.date.day.ordinalize}") %></td>
        <td><%= @tracker.task %></td>
        <td><%= @tracker.subtask_1 %></td>
        <td><%= @tracker.description %></td>
        <td><%= @tracker.hours %></td>
        <td><%= @tracker.start_time.strftime("%H:%M") %></td>
        <td><%= @tracker.end_time.strftime("%H:%M") %></td>
        <td><%= @tracker.payment %></td>
        <td><%= link_to "Edit", edit_track_path(:id => @tracker.id), :remote => true %>
        <td><%= link_to 'Destroy', @tracker, method: :delete, data: { confirm: 'Are you sure?' } %></td>

app/views/trackers/_edit_form.html.erb
<%= javascript_include_tag "project_selectors" %> <!-- PULL IN FUNCTIONALITY FOR LIMITING SELECTION LISTS BASED ON PREVIOUS SELECTION --> 

<!-- INITIALIZATION -->
    <% tracker = tracker %> <!-- generate local variable from local pulled in from render partial in edit.js.erb. local variable isn't recognized if I don't have this line included -->
    <% if tracker.nil? then tracker = Tracker.new end%> <!-- null handling to satisfy compiler -->

    <% @daily_tasks = DailyTask.all %>
    <% @project_umbrellas = ProjectUmbrella.all %>
    <% @projects = Project.all %>
    <% @weekly_goals = WeeklyGoal.all %>

<!-- FORM FIELDS -->
<%= form_for tracker do |form| %>

  <%= content_tag :div, :class => "td day", :data => {:provide => 'datepicker', 'date-format' => 'yyyy-mm-dd', 'date-autoclose' => 'true'} do
    form.text_field :date, class: 'form-control', placeholder: 'YYYY-MM-DD', value: tracker.date
  end %>

  <br><div>
    <%= form.label :project_umbrella %>
    <%=form.select :project_umbrella_id, ProjectUmbrella.all.collect {|pu| [ pu.name, pu.id ] }, :value => tracker.project_umbrella_id %>
  </div>

  <br><div class="td" id="project_select">
    <%= form.select :project_id, Project.all.collect{ | p | [p.name, p.id] }, :value => tracker.project_id %>
  </div>
  <br><div class="td" id="weekly_goal_select">
    <%=form.select :weekly_goal_id, WeeklyGoal.all.collect {|wg| [ wg.name, wg.id ] }, :value => tracker.weekly_goal_id %>
  </div>
  <br><div class="td daily_task">
    <%= form.select :daily_task_id, DailyTask.all.collect{ | dt | [dt.name, dt.id] }, :value => tracker.daily_task_id %>
  </div>
  <br><div class="td description">
    <%=form.text_field :description, :value => tracker.description, class: 'form_new_text_select' %>
  </div>
  <br><div class="td hours">
    <%=form.text_field :hours, :value => tracker.hours %>
  </div>
  <br><div class="td start_time">
    <%=form.time_select :start_time, {minute_step: 30}, :value => tracker.start_time %>
  </div>
  <br><div class="td end_time">
    <%=form.time_select :end_time, {minute_step: 30}, :value => tracker.end_time %>
  </div>
  <br><div class="td payment">
    <%=form.text_field :payment, :value => tracker.payment %>
  </div>
  <br><div class="td">
    <%=form.submit %>
  </div>
<% end %> 

app/views/trackers/_task_reset.html.erb
<span class="task_cat_title"><%= daily_task.category %></span>

app/views/trackers/create.js.erb
<%= @tracker.update_month %> //default the month number from the date into the month column
 <%= @tracker.save%> //save the tracker to the database
location.reload(true) //refresh the page

app/views/trackers/create_task_tracker.js.erb
// populate modal
document.getElementById("tracker-modal-title").innerHTML="New Tracker";
$('#tracker-modal-window-body').html("<%= j render partial: 'trackers/new_inherited_form', locals: {task: @task} %>");

// render modal
$('#tracker-modal-window').modal('show');

app/views/trackers/edit.html.erb
<h1>Edit Tracker</h1>



<%= link_to 'Back', tracker_path %>

app/views/trackers/edit.js.erb
// populate modal
document.getElementById("tracker-modal-title").innerHTML="Edit Tracker";

$('#tracker-modal-window-body').html("<%= j render partial: 'trackers/edit_form', locals: {tracker: @tracker} %>");

// render modal
$('#tracker-modal-window').modal('show');

app/views/trackers/index_legacy.html.erb
<!doctype html>
<html lang="en" ng-app='TimeTrack'>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>  

    <!-- JAVASCRIPT (assets/javascripts) -->
    <%= javascript_include_tag "project_selectors" %>
    <%= javascript_include_tag "modals_dropdowns" %>
    <%= javascript_include_tag "spa_functionality" %>
  </head>
  <body>

  <!-- post messages from controller go here -->
  <p id="notice"><%= notice %></p>

  <!-- BOOTSTRAP - NAVBAR -->
  <nav class="navbar navbar-light bg-light">
    <div class="btn-group">
      <button id="tracker_index_nav_btn" type="button" class="btn btn-primary nav-button" data-toggle="dropdown"><%= fa_icon('bars')%></button>
      <div class="dropdown-menu">
        <%= link_to "Trackers for Month", "month_index", method: :get, id: "tracker_index_nav_month_tracker_link" %>
        <br><%= link_to "Project List", :controller => "projects", :action => "index" %>
        <br><%= link_to "NT Process", :method => "post", :controller => "daily_tasks", :action => "nightly_task_processing" %>

      </div>
    </div>

    <span class="navbar-brand mb-0 h1">TimeTrack</span>

    <div>
      <%= Time.now.strftime('%m-%d-%Y')%><br>
      <%= Time.now.strftime('%H:%M')%>
    <div>
  </nav>
      
  <!--<%= button_to "NT Process",  {:controller => "daily_tasks", :action => "nightly_task_processing"} %> -->



<!-- /////////////////////////////////////////////////// -->
<!-- ////////// DAILY TASKS AND WEEKLY GOALS /////////// -->
<!-- /////////////////////////////////////////////////// -->

    <!-- Modal window for 'New' and 'Edit' task and goal functionality -->
    <div id="task-goal-modal-window" class="modal hide fade" role="dialog" aria-labelledby="task-goal-modal-window" aria-hidden="true">
      <div id="modal-dialog" class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <i class="fas fa-times" data-dismiss="modal" onclick="modalXClose()"></i>
            <h4 class="modal-title" id="task-goal-modal-title"></h4>
          </div>
          <div id="task-goal-modal-window-body" class="modal-body">

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

<!--     <div id="nonmodal_content"> -->
    <div id="goals_tasks" class="rounded" ng-controller='TaskGoalContent'>
      <!-- link to trigger modal window for 'New' task and goal functionality -->
      <div id="task_goal_toggle_view">
        <h2>Project Goals and Tasks</h2>
        <button id="today-tasks-btn" name="today-tasks-btn" type="button" class="{{activeTaskToggle}} goal-task-toggle-btn" ng-model="todayTasksBtn" ng-click="loadTrackerTodayTasks();">Today</button>
        <button id="weekly-goals-btn" type="button" class="{{activeGoalToggle}} goal-task-toggle-btn" ng-model="weeklyGoalsBtn" ng-click="loadTrackerWeeklyGoals();">This Week</button>
      </div>
      <div id="task_goal_content">
        <h3 id="task_heading">{{taskHeading}}</h3>
        <%= link_to new_daily_task_path, class: 'btn add_new_btn', remote: true do %>
          <i class="fas fa-plus"></i>
        <% end %>

        <!-- DISPLAY TODAYS TASKS -->

<div id="daily_tasks" class="project-content">
  
  <div class="container-fluid">
    <div class="row">
      <% todays_tasks = get_todays_tasks %> <!-- return all tasks marked true for 'is_daily_task' -->
      <% todays_tasks.each do |task| %> <!-- loop through all daily tasks -->
        <% unless task.completed %>
          <div class="col-md-4">
            <div class="daily_task_cat">
              <button type="button" class="nav-button daily_task_btn" data-toggle="dropdown">
                <span class="task_project"><%= task.project.name %></span>
                <span class="daily_task"><%= task.name %></span> 
                <i class="far fa-clock today-task-clock"></i>
              </button> 
              <div class="dropdown-menu">
                <%= link_to 'Edit Task', {:controller => "daily_tasks", :action => "edit", :id => task.id}, remote: true %> <!--link to modal window for 'Edit' task functionality -->
                <br><% if task.is_today_task == true then %>
                  <%= link_to "Remove from Today's Tasks", {:controller => "daily_tasks", :action => "remove_today_task", :daily_task => task.id} %>
                <% else %>
                  <%= link_to "Mark for Today's Tasks", {:controller => "daily_tasks", :action => "mark_today_task", :daily_task => task.id} %>
                <% end %>
                <br><%= link_to "Complete Task", complete_task_path(task_id: task.id) %>
                <br><%= link_to "Add Tracker", create_task_tracker_path(task_id: task.id), remote: true %>
                <br><%= link_to "Delete Task", {:controller => "daily_tasks", :action => "delete_task", :daily_task => task.id}, data: {confirm: "Are you sure you want to delete this Daily Task?"}  %>

              </div> <!-- end dropdown-menu -->  
            </div> <!-- end daily_task_cat -->
          </div> <!-- end col-md-4 -->
        <% else %>
          <% if task.active %>
            <div id="weekly_goal_completed" class="weekly_goal_completed col-sm-4">
              <div id="completed_check"><%= fa_icon('check-circle') %></div>
              <span class="completed_task_project">
                  <% if !task.weekly_goal.nil? then %>
                    <% if !task.weekly_goal.project.nil? then %>
                      <%= task.weekly_goal.project.name %>
                    <% end %>
                  <% end %>
              </span>
              <span class="completed_daily_task"><%= task.name %></span>
            </div> <!-- end weekly_goal_completed -->
          <% end %>
        <% end %>
      <% end %>
    </div> <!-- row -->
  </div> <!-- container -->
</div> <!-- end daily_tasks -->
        
        
      </div> <!-- end task_goal_content -->
    </div> <!-- end daily_tasks -->

<!-- /////////////////////////////////////////////////// -->
<!-- /////////////////// TRACKERS ////////////////////// -->
<!-- /////////////////////////////////////////////////// -->

    <!-- Modal window for 'New' and 'Edit' tracker functionality -->
    <div id="tracker-modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div id="modal-dialog" class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" id="tracker-modal-title">New Tracker</h4>
            <i class="fas fa-times" data-dismiss="modal" onclick="modalXClose()"></i>
          </div>
          <div id="tracker-modal-window-body" class="modal-body">
            <!-- form dynamically added in edit.js.erb or new.js.erb -->
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary">Save changes</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div> <!-- end tracker-modal-window -->

    <!-- Tracker Table -->
    <table id="daily_trackers" class="table">
      <div class="table_caption">
        <h2 id="tracker-title">Today's Trackers <%= link_to new_tracker_path, id: 'index-new-tracker', class: 'btn add_new_btn', remote: true do %>
        <i class="fas fa-plus"></i>
      <% end %></h2>
      </div>
      <thead>
        <tr>
          <th>Day</th>
          <th>Project Umbrella</th>
          <th>Project</th>
          <th>Weekly Goal</th>
          <th>Daily Task</th>
          <th>Description</th>
          <th>Hours</th>
          <th>Start Time</th>
          <th>End Time</th>
          <th></th>
          <th></th>
      </thead>
      <tbody id="idx_trackers" >
        <% curr_day = Time.now.day %>
        <% @day_trackers = get_days_trackers(curr_day) %> <!-- return an array of trackers for day i -->
        <% if @day_trackers.empty? then %> <!-- if array is empty display 'no info' line -->
          <tr class="empty_day">
            <% i_day = Date.new(@year, @month, curr_day) %>
            <div class="td"><%= i_day.strftime("%a #{i_day.day.ordinalize}") %></div>
            <div class="td">No Trackers Logged :(</div>
          </tr>
        <% else %> <!-- if array is not empty, format and show all trackers for the day -->
          <% @day_trackers.each do |tracker| %>
            <tr id=<%=tracker.id%>>
              <td><%= tracker.date.strftime("%a #{tracker.date.day.ordinalize}") %></td>
              <td>
                <% if !tracker.project_umbrella_id.nil? then %> <!-- first check for unlinked project umbrella-->
                  <%= ProjectUmbrella.find(tracker.project_umbrella_id).name %>
                <% else %> <!-- if not stored directly, get project umbrella through linking -->
                  <% if !tracker.daily_task.nil? then %> 
                    <% if !tracker.daily_task.weekly_goal.nil? then %>
                      <% if !tracker.daily_task.weekly_goal.project.nil? then %>
                        <% if !tracker.daily_task.weekly_goal.project.project_umbrella.nil? then %>
                          <%= tracker.daily_task.weekly_goal.project.project_umbrella.name %>
                        <% end %>
                      <% end %>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
              <td>
                <% if !tracker.project_id.nil? then %> <!-- first check for unlinked project umbrella-->
                  <%= Project.find(tracker.project_id).name %>
                <% else %> <!-- if not stored directly, get project umbrella through linking -->
                  <% if !tracker.daily_task.nil? then %>
                    <% if !tracker.daily_task.weekly_goal.nil? then %>
                      <% if !tracker.daily_task.weekly_goal.project.nil? then %>
                        <%= tracker.daily_task.weekly_goal.project.name %>
                      <% end %>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
              <td>
                <% if !tracker.daily_task.nil? then %>
                  <% if !tracker.daily_task.weekly_goal.nil? then %>
                    <%= tracker.daily_task.weekly_goal.name %>
                  <% end %>
                <% end %>
              </td>
              <td>
                <% if !tracker.daily_task.nil? then %>
                  <%= tracker.daily_task.name %>
                <% end %>
              </td>
              <td><%= tracker.description %></td>
              <td><%= tracker.hours %></td>
              <td><%= tracker.start_time.strftime("%H:%M") %></td>
              <td><%= tracker.end_time.strftime("%H:%M") %></td>
              <td><%= link_to 'Edit', edit_tracker_path(tracker.id), remote: true %></td>
              <td><%= link_to 'Destroy', tracker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody> <!-- end idx_trackers -->
    </table> <!-- end daily_trackers -->
    <!-- </div> end nonmodal-content -->
  <!-- </div> -->
  </body>
</html>

app/views/trackers/modal.html.erb
<div class="modal" id="mainModal" tabindex="-1" role="dialog" aria-labelledby="mainModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="mainModalLabel">
          <%= yield :title if content_for? :title %>&nbsp;
        </h4>
      </div>

      <%= yield %>
    </div>
  </div>
</div>

app/views/trackers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @tracker.date %>
</p>

<p>
  <strong>Task:</strong>
  <%= @tracker.project_id %>
</p>

<p>
  <strong>Subtask 1:</strong>
  <%= @tracker.weekly_goal_id %>
</p>

<p>
  <strong>Subtask 2:</strong>
  <%= @tracker.description %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @tracker.hours %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @tracker.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @tracker.end_time %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @tracker.payment %>
</p>

<%= link_to 'Edit', edit_tracker_path(@tracker) %> |
<%= link_to 'Back', trackers_path %>